export { default as AppMain } from './appMain'
export { default as NavBar } from './navBar.vue'
// export { default as Settings } from './Settings'
export { default as SideBar } from './sideBar/sideBar.vue'
export { default as TabsView } from './tabsView/tabsView.vue'
